version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8080 --noreload
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env
    environment:
      DB_HOST: db
    networks:
      - mynetwork
  db:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - mynetwork

volumes:
  static_volume:
  db_data:

networks:
  mynetwork: